# Generated by Django 4.2.2 on 2023-06-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departamento', models.CharField(max_length=200)),
                ('Descripcion_del_Problema', models.TextField(blank=True)),
                ('Estado', models.BooleanField(default=False)),
                ('Fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
