# Generated by Django 3.2.18 on 2023-06-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Departamento',
            field=models.CharField(max_length=200, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Descripcion_del_Problema',
            field=models.TextField(blank=True, verbose_name='Descripcion del Problema'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Estado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de envio'),
        ),
    ]
